-- Dashboard dedicated schema (public)
-- Run this on the DASHBOARD Supabase project.

create table if not exists public.dashboard_sync_state (
  table_name text primary key,
  last_updated_at timestamptz not null default '1970-01-01T00:00:00Z',
  last_id text not null default '',
  status text not null default 'idle' check (status in ('idle', 'running', 'failed')),
  started_at timestamptz null,
  finished_at timestamptz null,
  last_error text null,
  rows_read bigint not null default 0,
  rows_written bigint not null default 0,
  duration_ms bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.dashboard_sync_runs (
  id bigint generated by default as identity primary key,
  run_uuid uuid not null unique default gen_random_uuid(),
  mode text not null check (mode in ('incremental', 'backfill')),
  status text not null default 'running' check (status in ('running', 'ok', 'failed')),
  source_project text null,
  target_project text null,
  started_at timestamptz not null default now(),
  finished_at timestamptz null,
  duration_ms bigint null,
  tables_synced jsonb not null default '[]'::jsonb,
  total_rows_read bigint not null default 0,
  total_rows_written bigint not null default 0,
  rows_deleted_reconciled bigint not null default 0,
  error_message text null
);

create table if not exists public.dashboard_sync_lock (
  lock_name text primary key,
  owner_id text null,
  acquired_at timestamptz null,
  heartbeat_at timestamptz null,
  locked_until timestamptz null,
  updated_at timestamptz not null default now()
);

insert into public.dashboard_sync_lock(lock_name)
values ('dashboard_sync')
on conflict (lock_name) do nothing;

create or replace function public.dashboard_acquire_sync_lock(
  p_lock_name text,
  p_owner_id text,
  p_ttl_seconds integer default 600
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ok boolean := false;
begin
  insert into public.dashboard_sync_lock(lock_name, owner_id, acquired_at, heartbeat_at, locked_until, updated_at)
  values (
    p_lock_name,
    p_owner_id,
    now(),
    now(),
    now() + make_interval(secs => p_ttl_seconds),
    now()
  )
  on conflict (lock_name) do update
  set owner_id = excluded.owner_id,
      acquired_at = now(),
      heartbeat_at = now(),
      locked_until = now() + make_interval(secs => p_ttl_seconds),
      updated_at = now()
  where
    public.dashboard_sync_lock.locked_until is null
    or public.dashboard_sync_lock.locked_until < now()
    or public.dashboard_sync_lock.owner_id = excluded.owner_id;

  get diagnostics v_ok = row_count;
  return coalesce(v_ok, false);
end;
$$;

create or replace function public.dashboard_heartbeat_sync_lock(
  p_lock_name text,
  p_owner_id text,
  p_ttl_seconds integer default 600
)
returns boolean
language sql
security definer
set search_path = public
as $$
  with moved as (
    update public.dashboard_sync_lock
    set heartbeat_at = now(),
        locked_until = now() + make_interval(secs => p_ttl_seconds),
        updated_at = now()
    where lock_name = p_lock_name
      and owner_id = p_owner_id
    returning 1
  )
  select exists(select 1 from moved);
$$;

create or replace function public.dashboard_release_sync_lock(
  p_lock_name text,
  p_owner_id text
)
returns boolean
language sql
security definer
set search_path = public
as $$
  with moved as (
    update public.dashboard_sync_lock
    set owner_id = null,
        acquired_at = null,
        heartbeat_at = null,
        locked_until = null,
        updated_at = now()
    where lock_name = p_lock_name
      and owner_id = p_owner_id
    returning 1
  )
  select exists(select 1 from moved);
$$;

create table if not exists public.dash_visits (
  id uuid primary key,
  cliente_id uuid null,
  visit_date date null,
  perfil_visita text null,
  visit_type text null,
  supervisor_reason text null,
  register_mode text null,
  completed_at timestamptz null,
  no_visit_reason text null,
  assigned_to_user_id uuid null,
  assigned_to_name text null,
  completed_vidas numeric null,
  deleted_at timestamptz null,
  created_at timestamptz null,
  updated_at timestamptz null
);

create table if not exists public.dash_aceite_digital (
  id bigint generated by default as identity primary key,
  source_id uuid unique,
  entry_date date null,
  vendor_user_id uuid null,
  vendor_name text null,
  vidas numeric null,
  deleted_at timestamptz null,
  created_at timestamptz null,
  updated_at timestamptz null
);

create table if not exists public.dash_clientes (
  id uuid primary key,
  codigo text null,
  empresa text null,
  nome_fantasia text null,
  data_da_ultima_visita date null,
  cidade text null,
  bairro text null,
  uf text null,
  situacao text null,
  vendedor text null,
  categoria text null,
  grupo text null,
  deleted_at timestamptz null,
  created_at timestamptz null,
  updated_at timestamptz null
);

create table if not exists public.dash_profiles (
  id uuid primary key,
  user_id uuid unique,
  supervisor_id uuid null,
  role text null,
  display_name text null,
  nome text null,
  deleted_at timestamptz null,
  created_at timestamptz null,
  updated_at timestamptz null
);

create index if not exists idx_dash_visits_visit_date on public.dash_visits(visit_date);
create index if not exists idx_dash_visits_assigned_to_user_id on public.dash_visits(assigned_to_user_id);
create index if not exists idx_dash_visits_updated_at_id on public.dash_visits(updated_at, id);
create index if not exists idx_dash_aceite_entry_date on public.dash_aceite_digital(entry_date);
create index if not exists idx_dash_aceite_updated_at_source_id on public.dash_aceite_digital(updated_at, source_id);
create index if not exists idx_dash_clientes_cidade on public.dash_clientes(cidade);
create index if not exists idx_dash_clientes_updated_at_id on public.dash_clientes(updated_at, id);
create index if not exists idx_dash_profiles_role on public.dash_profiles(role);
create index if not exists idx_dash_profiles_updated_at_id on public.dash_profiles(updated_at, id);
