create table if not exists public.kpi_imports (
  id uuid primary key default gen_random_uuid(),
  created_by_user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_by_name text null,
  source_filename text not null,
  rows_in_file integer not null default 0 check (rows_in_file >= 0),
  valid_rows integer not null default 0 check (valid_rows >= 0),
  ignored_rows integer not null default 0 check (ignored_rows >= 0),
  unique_codes integer not null default 0 check (unique_codes >= 0),
  unvalidated_codes integer not null default 0 check (unvalidated_codes >= 0),
  status text not null default 'VALIDADO' check (status in ('VALIDADO', 'APLICADO')),
  detected_columns jsonb not null default '{}'::jsonb,
  found_codes integer null check (found_codes is null or found_codes >= 0),
  missing_codes integer null check (missing_codes is null or missing_codes >= 0),
  estimated_companies_updated integer null check (estimated_companies_updated is null or estimated_companies_updated >= 0),
  updated_rows integer null check (updated_rows is null or updated_rows >= 0),
  created_at timestamptz not null default now(),
  applied_at timestamptz null,
  applied_by_user_id uuid null references auth.users(id) on delete set null
);

create index if not exists kpi_imports_created_at_idx
  on public.kpi_imports(created_at desc);

create table if not exists public.kpi_import_rows (
  id bigint generated by default as identity primary key,
  import_id uuid not null references public.kpi_imports(id) on delete cascade,
  codigo text not null,
  vidas_in numeric not null check (vidas_in >= 0),
  vidas_out numeric not null check (vidas_out >= 0),
  categoria text not null,
  month_key text not null,
  source_row integer null,
  created_at timestamptz not null default now(),
  unique (import_id, codigo)
);

create index if not exists kpi_import_rows_import_idx
  on public.kpi_import_rows(import_id);

create index if not exists kpi_import_rows_codigo_idx
  on public.kpi_import_rows(codigo);

create table if not exists public.kpi_import_unvalidated_codes (
  id bigint generated by default as identity primary key,
  import_id uuid not null references public.kpi_imports(id) on delete cascade,
  codigo text not null,
  reason text not null check (reason in ('NAO_CADASTRADO', 'NAO_ATIVO')),
  created_at timestamptz not null default now(),
  unique (import_id, codigo)
);

create index if not exists kpi_import_unvalidated_import_idx
  on public.kpi_import_unvalidated_codes(import_id);

alter table public.kpi_imports enable row level security;
alter table public.kpi_import_rows enable row level security;
alter table public.kpi_import_unvalidated_codes enable row level security;

drop policy if exists "Supervisor or assistente full access on kpi_imports" on public.kpi_imports;
create policy "Supervisor or assistente full access on kpi_imports"
  on public.kpi_imports
  for all
  using (public.is_supervisor() or public.is_assistente())
  with check (public.is_supervisor() or public.is_assistente());

drop policy if exists "Supervisor or assistente full access on kpi_import_rows" on public.kpi_import_rows;
create policy "Supervisor or assistente full access on kpi_import_rows"
  on public.kpi_import_rows
  for all
  using (public.is_supervisor() or public.is_assistente())
  with check (public.is_supervisor() or public.is_assistente());

drop policy if exists "Supervisor or assistente full access on kpi_import_unvalidated_codes" on public.kpi_import_unvalidated_codes;
create policy "Supervisor or assistente full access on kpi_import_unvalidated_codes"
  on public.kpi_import_unvalidated_codes
  for all
  using (public.is_supervisor() or public.is_assistente())
  with check (public.is_supervisor() or public.is_assistente());
