-- Seed sample agenda rows for testing
insert into public.agenda (
  data_da_ultima_visita,
  consultor,
  cod_1,
  empresa,
  perfil_visita,
  corte,
  venc,
  valor,
  tit,
  endereco,
  bairro,
  cidade,
  uf,
  supervisor,
  vendedor,
  cod_2,
  nome_fantasia,
  grupo,
  situacao,
  obs_contrato_1,
  obs_contrato_2,
  dedupe_key,
  raw_row
) values
(
  timestamptz '2026-02-24 10:00:00-03',
  'Carlos Lima',
  'A001',
  'Clínica Sorriso Forte',
  'Recorrente',
  1200.50,
  300.00,
  1500.50,
  'Premium',
  'Av. Beira Mar, 1200',
  'Meireles',
  'Fortaleza',
  'CE',
  'Mariana Souza',
  'João Pereira',
  'A001-2',
  'Sorriso Forte',
  'Grupo A',
  'Agendado',
  'Contrato renovado',
  'Preferência manhã',
  'clinica sorriso forte|sorriso forte|2026-02-24|joao pereira',
  '{}'::jsonb
),
(
  timestamptz '2026-02-23 14:30:00-03',
  'Ana Costa',
  'B015',
  'Odonto Vida',
  'Primeira',
  800.00,
  150.00,
  950.00,
  'Standard',
  'Rua das Flores, 45',
  'Aldeota',
  'Fortaleza',
  'CE',
  'Mariana Souza',
  'Paulo Reis',
  'B015-2',
  'Odonto Vida',
  'Grupo B',
  'Confirmado',
  'Contrato pendente',
  'Solicitou proposta',
  'odonto vida|odonto vida|2026-02-23|paulo reis',
  '{}'::jsonb
),
(
  timestamptz '2026-02-22 09:15:00-03',
  'Rafael Gomes',
  'C210',
  'Clínica Bem Estar',
  'Recorrente',
  500.00,
  200.00,
  700.00,
  'Basic',
  'Av. Santos Dumont, 2200',
  'Papicu',
  'Fortaleza',
  'CE',
  'Juliana Matos',
  'João Pereira',
  'C210-2',
  'Bem Estar Odonto',
  'Grupo C',
  'Agendado',
  'Falar com gerente',
  'Visita pós-venda',
  'clinica bem estar|bem estar odonto|2026-02-22|joao pereira',
  '{}'::jsonb
)
on conflict (dedupe_key) do nothing;
